CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season VARCHAR(50) NOT NULL,
    match_date DATE NOT NULL,
    home_team VARCHAR(120) NOT NULL,
    away_team VARCHAR(120) NOT NULL,
    home_score INTEGER NOT NULL,
    away_score INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_matches_different_teams CHECK (LOWER(home_team) <> LOWER(away_team)),
    CONSTRAINT chk_matches_home_score_non_negative CHECK (home_score >= 0),
    CONSTRAINT chk_matches_away_score_non_negative CHECK (away_score >= 0)
);

CREATE INDEX idx_matches_season_date ON matches (season, match_date);
